#Allowed allUsers with run.invoker for both frontend and backend

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _REPO: cloudbuild-cloudrun  

steps:

# ===== BACKEND =====
- name: "gcr.io/cloud-builders/docker"
  args:
    [
      "build",
      "-t",
      "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/fastapi:latest",
      "./backend"
    ]

- name: "gcr.io/cloud-builders/docker"
  args:
    [
      "push",
      "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/fastapi:latest"
    ]

- name: "gcr.io/cloud-builders/gcloud"
  args:
    [
      "run", "deploy", "fastapi-service",
      "--image", "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/fastapi:latest",
      "--region", "${_REGION}",
      "--platform", "managed",
      "--allow-unauthenticated"
    ]


# ===== FRONTEND =====
- name: "gcr.io/cloud-builders/docker"
  args:
    [
      "build",
      "-t",
      "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:latest",
      "./frontend"
    ]

- name: "gcr.io/cloud-builders/docker"
  args:
    [
      "push",
      "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:latest"
    ]

- name: "gcr.io/cloud-builders/gcloud"
  args:
    [
      "run", "deploy", "frontend-service",
      "--image", "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:latest",
      "--region", "${_REGION}",
      "--platform", "managed",
      "--allow-unauthenticated",
      "--set-env-vars", "VITE_API_URL=https://fastapi-service-${PROJECT_ID}.a.run.app"
    ]

images:
- "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/fastapi:latest"
- "us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:latest"