options:
  logging: CLOUD_LOGGING_ONLY

steps:

# -------- BACKEND --------
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', '-t',
    'us-central1-docker.pkg.dev/$PROJECT_ID/cloudbuild-cloudrun-be-fe-ar/fastapi:latest',
    './backend'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloudbuild-cloudrun-be-fe-ar/fastapi:latest']

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'services', 'replace',
    './backend/cloudrun.yaml',
    '--region', 'us-central1'
  ]

# -------- FRONTEND --------
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', '-t',
    'us-central1-docker.pkg.dev/$PROJECT_ID/cloudbuild-cloudrun-be-fe-ar/frontend:latest',
    './frontend'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloudbuild-cloudrun-be-fe-ar/frontend:latest']

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'services', 'replace',
    './frontend/cloudrun.yaml',
    '--region', 'us-central1'
  ]

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/cloudbuild-cloudrun-be-fe-ar/fastapi:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/cloudbuild-cloudrun-be-fe-ar/frontend:latest'