apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fastapi-service
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/$PROJECT_ID/cloudbuild-cloudrun-be-fe/fastapi:latest
          ports:
            - containerPort: 8080
      timeoutSeconds: 300