apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: react-frontend
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/$PROJECT_ID/myrepo/frontend:latest
          env:
            - name: VITE_API_URL
              value: "https://fastapi-service-xxxxxxxxxx-uc.a.run.app"